# vai conter o que os comandos que vai estar no assistente 

commands: 
  # Hora
  - command:
    input: Que horas são?
    entity: time # categoria de comando
    action: getTime #sub categoria > saber a hora
  - command: 
    input: Me diga as horas.
    entity: time
    action: getTime
  - command:
    input:  Eu quero saber as horas.
    entity: time
    action: getTime
  # Data
  - command: 
    input: Qual é a data de hoje?
    entity: time
    action: getDate
  - command:
    input: Data de hoje. 
    entity: time
    action: getDate 
  # Tempo
  - command: 
    input: Previsão do tempo
    entity: weather
    action: getWeather 
  - command: 
    input: Como está o clima
    entity: weather
    action: getWeather 
  # Open
  - command: 
    input: Abrir google
    entity: open
    action:  
  - command: 
    input: Abra youtube
    entity: open
    action:  

# python3.8 nlu/train.yml

# python3.8 nlu/model.py
